<template>
	<div class="bots">
		<i-modal v-model="modalCreateBot" :title="$t('Create Bot')">
			<p slot="header">
				<Icon type="ios-information-circle" />
				<span>{{ $t('Create new bot') }}</span>
			</p>
			<div style="text-align: center">
				<i-form>
					<i-form-item :label="$t('Bot Name')">
						<i-input v-model="newBotName" />
					</i-form-item>
					<i-form-item :label="$t('Bot URL')">
						<i-input :value="newBotURL" :readonly="true" :disabled="true" />
						<small style="text-align: left !important; display: block">{{ $t('The URL of the bot will be autogenerated from the bot name') }}</small>
					</i-form-item>
					<i-form-item :label="$t('Email Address')">
						<i-input v-model="newBotEmail" type="email" />
					</i-form-item>
					<i-form-item :label="$t('Bot Description')">
						<i-input v-model="newBotDesc" />
					</i-form-item>
				</i-form>
			</div>
			<div slot="footer">
				<div>
					<Button type="error" size="large" long @click="cancelCreateBot">
						{{ $t("Cancel") }}
					</Button>
				</div>
				<div>
					<Button type="success" size="large" long @click="okCreateBot">
						{{ $t("Create") }}
					</Button>
				</div>
			</div>
		</i-modal>

		<i-modal
			v-model="modalDeleteBot"
			:title="$t('Delete Bot')"
			@on-ok="okDeleteBot"
			@on-cancel="cancelDeleteBot"
		>
			<p slot="header">
				<Icon type="ios-information-circle" />
				<span>{{ $t("Delete Bot confirmation") }}</span>
			</p>
			<div style="text-align: center">
				<p>{{ $t("Deleting the bot is irreversable") }}</p>
				<p>{{ $t("Do you still want to delete it") }}</p>
			</div>
			<div slot="footer">
				<div>
					<Button type="success" size="large" long @click="cancelDeleteBot">
						{{ $t("Cancel") }}
					</Button>
				</div>
				<div>
					<Button type="error" size="large" long @click="okDeleteBot">
						{{ $t("Delete") }}
					</Button>
				</div>
			</div>
		</i-modal>

		<i-modal
			v-model="modalBotCreated"
			:title="$t('Bot Created')"
			@on-ok="
				() => {
					username = '';
					password = '';
					modalBotCreated = false;
				}
			"
		>
			<p>{{ $t("The bot has been created successfully") }}</p>
			<p>{{ $t("Botfront username: ") + username }}</p>
			<p>{{ $t("Botfront password: ") + password }}</p>
		</i-modal>

		<i-modal
			v-model="modalBotDeleted"
			:title="$t('Bot Deleted')"
			@on-ok="modalBotDeleted = false"
		>
			<p>{{ $t("The bot has now been flagged for deletion") }}</p>
		</i-modal>

		<i-modal
			v-model="modalError"
			:title="$t('Error')"
			@on-ok="modalError = false"
		>
			{{ $t(modalErrorMsg) }}
		</i-modal>

		<Card>
			<p slot="title">
				{{ $t("Bot Management") }}
			</p>
			<i-button
				slot="extra"
				type="success"
				:style="{ float: 'right' }"
				@click="clickCreateBot()"
			>
				{{ $t("Create new bot") }}
			</i-button>
			<br :style="{ clear: 'both' }" />
			<br />
			<Table width="100%" border :columns="botColumns" :data="botData">
				<template slot="timestamp" slot-scope="{ column, row }">
					<Tooltip placement="top" transfer>
						<Time :time="row[column.key]" />
						<Time slot="content" :time="row[column.key]" type="datetime" />
					</Tooltip>
				</template>

				<template slot="status" slot-scope="{ row }">
					<span v-if="row.status === 'errored'" style="color: red">{{ $t(states.errorStatus[states.errorStatus.findIndex((status) => status.status === row.status)].title) }}</span>
					<span v-else-if="row.status === 'removing'">{{ $t(states.removeStatus[states.removeStatus.findIndex((status) => status.status === row.status)].title) }}</span>
					<span v-else style="color: green">{{ $t(states.deployStatus[states.deployStatus.findIndex((status) => status.status === row.status)].title) }}</span>
				</template>
			</Table>
		</Card>
	</div>
</template>

<script lang="ts">
import Axios from "axios";
import { Component, Vue } from "vue-property-decorator";
// import { Route } from "vue-router";
import { CreateElement } from "vue";
import slugify from "slugify";
import * as generator from "@/name-generation.json";
import { sample, sampleSize, startCase } from "lodash";
import statuses from "../models/status";

import {
	Card,
	Icon,
	FormItem,
	Tooltip,
	Time,
	Collapse,
	Footer,
	Menu,
	MenuItem,
	Submenu,
	MenuGroup,
	DatePicker,
	Spin,
	Table,
	Input,
	// @ts-ignore
	Panel,
	Modal,
	Steps,
	// @ts-ignore
	Step,
} from "view-design";
@Component({
	components: {
		Card,
		Footer,
		Menu,
		MenuItem,
		Submenu,
		MenuGroup,
		DatePicker,
		Icon,
		FormItem,
		Tooltip,
		Time,
		Collapse,
		Spin,
		Table,
		Input,
		// @ts-ignore
		Panel,
		Modal,
		Steps,
		// @ts-ignore
		Step,
	},
})
export default class Bots extends Vue {
	public modalCreateBot: boolean = false;
	public modalBotCreated: boolean = false;
	public modalDeleteBot: boolean = false;
	public modalBotDeleted: boolean = false;
	public modalError: boolean = false;

	public modalErrorMsg: string = "";

	public newBotName: string = "";
	public newBotDesc: string = "";
	public newBotEmail: string = "";
	public username: string = "";
	public password: string = "";
	public deleteBot: any = undefined;

	public botData: any = [];

	public botColumns: any = [];

	public botStatusId: any;

	public deletableStatus = ["deployed", "errored"];

	public states = statuses;

	public async created() {
		this.botColumns = [
			{
				title: this.$t("Created"),
				key: "createdAt",
				slot: "timestamp",
			},
			{
				title: this.$t("Modified"),
				key: "updatedAt",
				slot: "timestamp",
			},
			{
				title: this.$t("Status"),
				key: "status",
				slot: "status",
			},
			{
				title: this.$t("Name"),
				key: "name",
			},
			{
				title: this.$t("Description"),
				key: "desc",
			},
			{
				title: this.$t("Actions"),
				fixed: "right",
				render: (h: CreateElement, params: any) =>
					h("div", [
						h(
							"Button",
							{
								props: {
									type: "default",
									size: "small",
								},
								on: {
									click: () => {
										this.$router.push({
											name: "Bot",
											params: { id: params.row._id },
										});
										// if(params.row.status === "deployed") {
										// 	// Edit credentials
										// } else {
										// 	// @ts-ignore
										// 	Modal.error({
										// 		title: this.$t("Error"),
										// 		content: this.$t("You can only edit bot credentials once the bot has been deployed")
										// 	});
										// }
									},
								},
							},
							this.$t("Details") as string
						),
						h(
							"Button",
							{
								props: {
									type: "error",
									size: "small",
								},
								on: {
									click: async () => {
										if (
											params.row.status === "deployed" ||
											params.row.status === "errored" ||
											params.row.status === "removing"
										) {
											this.deleteBot = params.row._id;
											this.modalDeleteBot = true;
										} else {
											// @ts-ignore
											Modal.error({
												title: this.$t("Error"),
												content: this.$t(
													"Bot cannot be removed whilst it is being processed"
												),
											});
										}
									},
								},
							},
							this.$t("Delete") as string
						),
					]),
			},
		];
		this.loadBots();
		// setup timer to check and update status of bots every 30 seconds
		this.botStatusId = setInterval(this.getStatus, 30000);
	}

	public beforeDestroy() {
		clearInterval(this.botStatusId);
	}

	public async loadBots() {
		Axios.get("/bots").then((res) => {
			if (res.data.success === true) {
				this.botData = res.data.bots;
			} else {
				throw this.$t("Error communicating with the server.");
			}
		});
	}

	public clickCreateBot() {
		this.newBotName = this.generateName();
		this.modalCreateBot = true;
	}

	public generateName() {
		const superb = sample(generator.superb);
		const names = sampleSize(generator.names, 3);
		return startCase(`${superb} ${names.join(" ")}`);
	}

	public async okCreateBot() {
		this.modalCreateBot = false;

		await Axios.post("/bots/add", {
			name: this.newBotName,
			desc: this.newBotDesc,
			email: this.newBotEmail
		}).then(async (res) => {
			if (res.data.success === true) {
				this.password = res.data.password;
				this.username = this.newBotEmail;
				this.modalBotCreated = true;
			}
		});

		this.newBotDesc = "";
		this.newBotName = "";
		this.newBotEmail = "";

		this.loadBots();
	}

	public cancelCreateBot() {
		this.newBotName = "";
		this.newBotDesc = "";
		this.newBotEmail = "";
		this.modalCreateBot = false;
	}

	public async okDeleteBot() {
		await Axios.delete(`/bots/${encodeURIComponent(this.deleteBot)}`).then(
			(res) => {
				if (res.data.success === true) {
					this.modalBotDeleted = true;
				} else {
					this.modalErrorMsg = "Failed to remove bot";
					this.modalError = true;
				}
			}
		);
		this.loadBots();
		this.modalDeleteBot = false;
	}

	public cancelDeleteBot() {
		this.deleteBot = undefined;
		this.modalDeleteBot = false;
	}

	public getStatus() {
		console.log("Getting bots status");
		// Get status of all bots
		Axios.get("/bots/bot-status").then((res) => {
			if (res.data.success === true) {
				const bots = res.data.bots;
				for (const bot of bots) {
					// Search for _id in botData
					const index = this.botData.findIndex(
						(element: any) => element._id === bot._id
					);
					if (this.botData[index].status !== bot.status) {
						this.botData[index].status = bot.status;
					}
				}
			}
		});
	}

	public get newBotSlug() {
		return slugify(this.newBotName, {
			replacement: "-", // replace spaces with replacement character, defaults to `-`
			lower: true, // convert to lower case, defaults to `false`
			strict: false, // strip special characters except replacement, defaults to `false`
			locale: "fi", // language code of the locale to use
			trim: true, // trim leading and trailing replacement chars, defaults to `true`
		});
	}

	public get newBotURL() {
		const protocol = "https://";
		const url = "-jamk.neuvo.ai";
		const slug = this.newBotSlug;
		return `${protocol}${slug}${url}`;
	}
}
</script>

<style lang="scss">
.map-wrapper {
	background: #fff !important;
}
.ivu-layout-content {
	position: relative;
}

.ivu-layout-content > div.stats {
	padding: 0;
}

.ivu-picker-panel-body-wrapper.ivu-picker-panel-with-sidebar {
	padding-left: 200px;
}

.ivu-picker-panel-sidebar {
	width: 200px;
	margin-left: -200px;
}

.ivu-date-picker-rel > span {
	padding: 20px;
	margin: 0 -20px;
}

.ivu-menu-item.apply {
	font-weight: bold;
	&.disabled {
		opacity: 0.3;
		pointer-events: none;
		cursor: disabled;
	}
}

.ivu-menu-primary.ivu-menu-horizontal
	.ivu-menu-item
	.ivu-date-picker
	.ivu-select-dropdown {
	top: 50px !important;
	color: var(--primary-color);
}

.ivu-menu-horizontal .ivu-menu-submenu.language-dropdown .ivu-select-dropdown {
	height: 1000px;
	overflow-y: scroll;
	max-height: 80vh;
}

.ivu-card {
	margin: 20px 0;
	.ivu-card-head {
		background: #f7f7f7;
	}
}

.ivu-notice-desc {
	text-align: left !important;
}
.intent-confidence {
	hr {
		margin: 20px 0;
		display: block;
		border: 0;
		background: #dcdee2;
		height: 1px;
	}
}
</style>
